### ISSUE TITLE
Not compatible with intl 0.18.0

### ISSUE THREAD

**Issue by ttzein6** [mjablecnik/MyLogger#1]
Need an urgent update

**Comment by r4faelferreir4** [comment]
@mjablecnik you updated the dependencies but on pub.dev there is not a new version with the fix. The alternative right now is to use dependency_overrides on master branch

**Comment by mjablecnik** [comment]
@r4faelferreir4 Thank you for your remind. I probably forgot to publish it. 
Latest version of MyLogger with dependency updates is already deployed. :)
