### ISSUE TITLE
Compatibility with android 13+

### ISSUE THREAD

**Issue by Harishwarrior** [mjablecnik/MyLogger#10]
Hi,
Does this code even work in Android 13?
```
    } else {
      directory = await getExternalStorageDirectory();
    }
```

in Logexporter. As we know Android 13 won't allow access to external storage

**Comment by Harishwarrior** [comment]
Reference: https://developer.android.com/reference/android/Manifest.permission#WRITE_EXTERNAL_STORAGE

**Comment by mjablecnik** [comment]
I didn't test it so I don't know if it works for Android 13+. You can check it and let me know then.

**Comment by Harishwarrior** [comment]
> I didn't test it so I don't know if it works for Android 13+. You can check it and let me know then.

It is not working in android 13. We can use document directory instead.
