### ISSUE TITLE
Best way to assess log file size

### ISSUE THREAD

**Issue by nicolasvahidzein** [mjablecnik/MyLogger#7]
Hello,

I was wondering if there was a way to figure out the log file size. I would like to upload the log file once it reaches a certain size but not quite sure how to go about that.

Cheers and thanks again for a wonderful package.

**Comment by mjablecnik** [comment]
Hello,
You can export your logs:
```
File fileExport = await MyLogger.logs.export(
  fileName: "export-all-logs",
  exportType: FileType.TXT,
  filter: LogFilter.all(),
);
```
[And check file size with code](https://stackoverflow.com/questions/53036328/how-do-i-check-the-file-size-of-a-video-in-flutter-before-uploading):
```
double getFileSize(File file){      
    int sizeInBytes = file.lengthSync();
    double sizeInMb = sizeInBytes / (1024 * 1024);
    return sizeInMb;
}
```

**Comment by nicolasvahidzein** [comment]
Thank you so much. 🙏🏽
