### ISSUE TITLE
Bad idea to use in production on every function?

### ISSUE THREAD

**Issue by nicolasvahidzein** [mjablecnik/MyLogger#8]
I love this package and i want to use it to print all my functions and important events in production regardless. Will this have a significant impact on my app you think?

I am asking instead of testing it first because it will be a few days of intense work and i would like to know if this is a good idea or not before i venture down that path.

Thanks for your insight.

**Comment by mjablecnik** [comment]
Hello, I think that it would not have any significant impact on your app..

**Comment by nicolasvahidzein** [comment]
Thank you so much, it is working great actually. Thanks @mjablecnik
